/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsuaJNI {
  public final static native void delete_PjsuaAppCallback(long jarg1);
  public final static native void PjsuaAppCallback_onStarted(long jarg1, PjsuaAppCallback jarg1_, String jarg2);
  public final static native void PjsuaAppCallback_onStartedSwigExplicitPjsuaAppCallback(long jarg1, PjsuaAppCallback jarg1_, String jarg2);
  public final static native void PjsuaAppCallback_onStopped(long jarg1, PjsuaAppCallback jarg1_, int jarg2);
  public final static native void PjsuaAppCallback_onStoppedSwigExplicitPjsuaAppCallback(long jarg1, PjsuaAppCallback jarg1_, int jarg2);
  public final static native void PjsuaAppCallback_onCallVideoStart(long jarg1, PjsuaAppCallback jarg1_);
  public final static native void PjsuaAppCallback_onCallVideoStartSwigExplicitPjsuaAppCallback(long jarg1, PjsuaAppCallback jarg1_);
  public final static native long new_PjsuaAppCallback();
  public final static native void PjsuaAppCallback_director_connect(PjsuaAppCallback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void PjsuaAppCallback_change_ownership(PjsuaAppCallback obj, long cptr, boolean take_or_release);
  public final static native void WindowHandle_window_set(long jarg1, WindowHandle jarg1_, long jarg2);
  public final static native long WindowHandle_window_get(long jarg1, WindowHandle jarg1_);
  public final static native void WindowHandle_setWindow(long jarg1, WindowHandle jarg1_, Object jarg2);
  public final static native long new_WindowHandle();
  public final static native void delete_WindowHandle(long jarg1);
  public final static native void setVideoWindow(long jarg1, WindowHandle jarg1_);
  public final static native int pjsuaStart();
  public final static native void pjsuaDestroy();
  public final static native int pjsuaRestart();
  public final static native void setCallbackObject(long jarg1, PjsuaAppCallback jarg1_);

  public static void SwigDirector_PjsuaAppCallback_onStarted(PjsuaAppCallback jself, String msg) {
    jself.onStarted(msg);
  }
  public static void SwigDirector_PjsuaAppCallback_onStopped(PjsuaAppCallback jself, int restart) {
    jself.onStopped(restart);
  }
  public static void SwigDirector_PjsuaAppCallback_onCallVideoStart(PjsuaAppCallback jself) {
    jself.onCallVideoStart();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
