/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class WindowHandle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WindowHandle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WindowHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsuaJNI.delete_WindowHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWindow(SWIGTYPE_p_void value) {
    pjsuaJNI.WindowHandle_window_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getWindow() {
    long cPtr = pjsuaJNI.WindowHandle_window_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setWindow(Object surface) {
    pjsuaJNI.WindowHandle_setWindow(swigCPtr, this, surface);
  }

  public WindowHandle() {
    this(pjsuaJNI.new_WindowHandle(), true);
  }

}
